-- Few of rare SQL queries


-- Using UNION ALL and getting limit 1 asc and desc
SELECT CITY, LEN FROM 
    ( SELECT * ,LENGTH(CITY) LEN FROM STATION ORDER BY LEN DESC LIMIT 1 ) LONGEST
UNION ALL 
SELECT CITY, LEN FROM 
    ( SELECT * ,LENGTH(CITY) LEN FROM STATION ORDER BY LEN,CITY ASC LIMIT 1 ) SHORTEST


-- Regex Usage
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[aeiouAEIOU]' ORDER BY CITY;
SELECT DISTINCT CITY FROM STATION WHERE CITY NOT REGEXP '^[aeiouAEIOU]' ORDER BY CITY;
SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '^[^AEIOU].*[^aeiou]$'; -- do not start and end with vowels.

-- RIGHT()
SELECT Name FROM STUDENTS WHERE Marks > 75 ORDER BY RIGHT(Name, 3), ID ASC; -- here names ending with Aina and Amina will have sorted Aina,Amina.

